name: workflow_test
on: push
jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: sudo apt-get install libcunit1 libcunit1-doc libcunit1-dev
      - name: checkout repo
        uses: actions/checkout@main
      - name: Run tests
        run:  |
        ls
        make test
      
      - name: Install test report dependencies
        run: sudo apt-get install xsltproc

      - name: Transform and display Test Report
        id: transform
        run: |
          xsltproc test_report_converter.xsl test_results-Results.xml >> "$GITHUB_STEP_SUMMARY"